name: Gradle CI with Email Notification

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - stage

  schedule:
    - cron: '0 7 * * *'  # Runs at 12:30 PM IST daily

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILE_ACTIVE: ${{ vars.SPRING_PROFILE_ACTIVE }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Print API key and spring_profile_active
        run: |
          echo "🔐 API Key: $API_KEY"
          echo "🌱 spring_profile_active: $SPRING_PROFILE_ACTIVE"

      - name: Run Cucumber tests with environment
        run: ./gradlew clean test -Dcucumber.features=src/test/resources/features -Dapi_key=$API_KEY -Dspring_profile_active=$SPRING_PROFILE_ACTIVE
