name: Gradle CI with Email Notification

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - stage

  schedule:
    - cron: '45 7 * * *'  # Runs at 1:15 PM IST daily

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILE_ACTIVE: ${{ vars.SPRING_PROFILE_ACTIVE }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew


      - name: Run Cucumber tests with environment
        run: ./gradlew clean test -Dcucumber.features=src/test/resources/features -DAPI_KEY=$API_KEY -DSPRING_PROFILE_ACTIVE=$SPRING_PROFILE_ACTIVE
